package dashboard;



import Changepassword.ChangePassword;
import java.awt.Image;
import java.io.*;
//import static java.awt.Image.SCALE_SMOOTH;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.sql.*;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Conntentpanel.ItemDisplay;
//import static Conntentpanel.ItemDisplay.p1;
import Layout.PanelItem;
import java.awt.Color;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.event.KeyEvent;
//import javax.swing.JButton;
//import javax.swing.table.DefaultTableModel;
import loginpage.LoginForm;
import static loginpage.LoginForm.getUserId;
import UserDisplay.userdetails1;
import javax.swing.JFrame;

/**
 *
 * @author Durai
 */
public class MainMenu extends javax.swing.JFrame {
    
    String s,s1;
    public static String PRODUCTNAME;
    
    /**
     * Creates new form MainMenu
     */
     
    void LoadProduct(String sql)
       
    {
         ItemDisplay a[] = new ItemDisplay[100];
        int i =0;
        int PRODUCTUSERID;
         try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/uzhavan","root","");
            Statement stmt = con.createStatement();

            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next())
            {
                a[i] = new ItemDisplay();
                byte[] img = rs.getBytes(4);
                ImageIcon image = new ImageIcon(img);
                Image in = image.getImage();
                Image myImg = in.getScaledInstance(319,178, Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myImg);
                a[i].photo.setIcon(newImage);

                
                a[i].productname.setText(rs.getString(3));
                a[i].rate.setText(rs.getString(6));
                a[i].instruction = rs.getString(7);
                a[i].minrate = rs.getString(5);
                a[i].description = rs.getString(8);
                a[i].USERIDPRODUCT = rs.getInt(2);
                a[i].name.setText(rs.getString(9));
                a[i].product_number.setText(String.valueOf(rs.getInt(1)));
                PRODUCTUSERID = rs.getInt(2);
                panelItem1.add(a[i]);
                panelItem1.validate();

                i++;
            }
        }
        catch(Exception ex)
        {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,ex,"Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();

        }
    }

     public MainMenu() {
        initComponents();
        
        
        try
        {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("error");
            }
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/collegedb","root","");
            
            //JOptionPane.showMessageDialog(null,"Connected");        
        }   
        catch(SQLException e)
        {
          JOptionPane.showMessageDialog(null,"Not Connected");
        }
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        home_jPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search_jPanel = new javax.swing.JPanel();
        user_name = new javax.swing.JLabel();
        user_id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel21 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        report_tf = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        reportUser_id = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        reprtUser_Name = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        result2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        minrate_t2 = new javax.swing.JTextField();
        model_t1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        instruction_t4 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        description_t5 = new javax.swing.JTextArea();
        img_text = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        yes_b = new javax.swing.JRadioButton();
        no_b = new javax.swing.JRadioButton();
        img = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        maxrate_t3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        productname_tf = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        validate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelItem1 = new Layout.PanelItem();
        jButton8 = new javax.swing.JButton();
        dashBoard_jPanel = new javax.swing.JPanel();
        home_jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        home_jPanel.setBackground(new java.awt.Color(0, 255, 204));
        home_jPanel.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/farmer.png"))); // NOI18N
        jLabel1.setText("UZHAVZN-ERS");
        jLabel1.setIconTextGap(50);
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(25, 6, 410, 45);

        search_jPanel.setBackground(new java.awt.Color(255, 255, 255));
        search_jPanel.setLayout(null);

        user_name.setBackground(new java.awt.Color(255, 255, 255));
        user_name.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        user_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_nameMouseClicked(evt);
            }
        });
        search_jPanel.add(user_name);
        user_name.setBounds(165, 6, 159, 48);

        user_id.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        search_jPanel.add(user_id);
        user_id.setBounds(80, 0, 93, 48);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user-info.png"))); // NOI18N
        search_jPanel.add(jLabel2);
        jLabel2.setBounds(9, 6, 45, 45);

        jPanel1.add(search_jPanel);
        search_jPanel.setBounds(570, 10, 330, 50);

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("Logout");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(1050, 10, 150, 40);

        home_jPanel.add(jPanel1);
        jPanel1.setBounds(0, 0, 1390, 60);

        jPanel21.setBackground(new java.awt.Color(204, 255, 204));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/interCropCultivator.jpg"))); // NOI18N
        jButton3.setText("load");
        jButton3.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 230, 230));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/drone.jpeg"))); // NOI18N
        jButton9.setOpaque(true);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 230, 230));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brushcutter.jpg"))); // NOI18N
        jButton10.setText("load");
        jButton10.setPreferredSize(new java.awt.Dimension(75, 23));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 230, 230));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stroke.jpg"))); // NOI18N
        jButton11.setText("jButton11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 230, 230));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trackter.jpg"))); // NOI18N
        jButton13.setText("jButton13");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 230, 230));

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pump.jpg"))); // NOI18N
        jButton12.setText("jButton12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 230, 230));

        jTabbedPane1.addTab("home", jPanel21);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Report user page ");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel18.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 37, 329, 68));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("User id :");
        jPanel18.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 169, 122, 34));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("User name :");
        jPanel18.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 122, 34));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Reason for reports:");
        jPanel18.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 160, 40));

        report_tf.setColumns(20);
        report_tf.setRows(5);
        jScrollPane4.setViewportView(report_tf);

        jPanel18.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 428, 172));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel18.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 256, 20));

        reportUser_id.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        reportUser_id.setForeground(new java.awt.Color(153, 153, 153));
        reportUser_id.setText("123");
        reportUser_id.setBorder(null);
        reportUser_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reportUser_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                reportUser_idFocusLost(evt);
            }
        });
        jPanel18.add(reportUser_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 278, 41));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel18.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 264, 256, 20));

        reprtUser_Name.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        reprtUser_Name.setForeground(new java.awt.Color(153, 153, 153));
        reprtUser_Name.setText("Name");
        reprtUser_Name.setBorder(null);
        reprtUser_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reprtUser_NameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                reprtUser_NameFocusLost(evt);
            }
        });
        jPanel18.add(reprtUser_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 280, 50));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back (1).png"))); // NOI18N
        jButton6.setText("Back");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton6.setIconTextGap(70);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 200, 50));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/upload.png"))); // NOI18N
        jButton7.setText("Sumit report");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton7.setIconTextGap(15);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 240, 50));

        result.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel18.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 500, 70));

        result2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        result2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel18.add(result2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, 490, 50));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report (2).png"))); // NOI18N
        jPanel18.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 70, 70));

        jTabbedPane1.addTab("help", jPanel18);

        jPanel20.setBackground(new java.awt.Color(204, 255, 255));
        jPanel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel20.setPreferredSize(new java.awt.Dimension(1080, 704));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Details of new Product ");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 0)));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 20)); // NOI18N
        jLabel9.setText(" Model Number :");

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        jLabel10.setText("Minimum-Rate :");

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        jLabel11.setText("Operator           :");

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        jLabel12.setText("Instruction       :");

        minrate_t2.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        minrate_t2.setForeground(new java.awt.Color(153, 153, 135));
        minrate_t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minrate_t2.setText("Minium fixed rate");
        minrate_t2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        minrate_t2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                minrate_t2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                minrate_t2FocusLost(evt);
            }
        });
        minrate_t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                minrate_t2KeyPressed(evt);
            }
        });

        model_t1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        model_t1.setForeground(new java.awt.Color(153, 153, 153));
        model_t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        model_t1.setText("AB2022VL0967");
        model_t1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        model_t1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        model_t1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                model_t1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                model_t1FocusLost(evt);
            }
        });
        model_t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model_t1ActionPerformed(evt);
            }
        });
        model_t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                model_t1KeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        jLabel13.setText("Description     :");

        instruction_t4.setColumns(20);
        instruction_t4.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        instruction_t4.setForeground(new java.awt.Color(153, 153, 153));
        instruction_t4.setLineWrap(true);
        instruction_t4.setRows(5);
        instruction_t4.setText(" Detailed instruction to handle the \nproduct");
        instruction_t4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        instruction_t4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                instruction_t4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                instruction_t4FocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(instruction_t4);

        description_t5.setColumns(20);
        description_t5.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        description_t5.setForeground(new java.awt.Color(153, 153, 153));
        description_t5.setRows(5);
        description_t5.setText(" Detailed description about the \nproduct ");
        description_t5.setWrapStyleWord(true);
        description_t5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        description_t5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                description_t5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                description_t5FocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(description_t5);

        img_text.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButton1.setBackground(new java.awt.Color(20, 22, 30));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-photo.png"))); // NOI18N
        jButton1.setText("Add Photo");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.setIconTextGap(14);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(yes_b);
        yes_b.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        yes_b.setText("yes");
        yes_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes_bActionPerformed(evt);
            }
        });

        buttonGroup1.add(no_b);
        no_b.setFont(new java.awt.Font("Arial Narrow", 0, 20)); // NOI18N
        no_b.setText("no");

        img.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        jLabel14.setText("Max - Rate        :");

        maxrate_t3.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        maxrate_t3.setForeground(new java.awt.Color(153, 153, 153));
        maxrate_t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxrate_t3.setText("Rate for 1-hour");
        maxrate_t3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        maxrate_t3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                maxrate_t3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                maxrate_t3FocusLost(evt);
            }
        });
        maxrate_t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                maxrate_t3KeyPressed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(20, 22, 30));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/upload.png"))); // NOI18N
        jButton2.setText("Upload");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.setIconTextGap(35);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        productname_tf.setBackground(new java.awt.Color(20, 22, 30));
        productname_tf.setFont(new java.awt.Font("Bahnschrift", 0, 20)); // NOI18N
        productname_tf.setForeground(new java.awt.Color(255, 255, 255));
        productname_tf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mustfill", "Drone", "Brushcutter", "Mini Power Weeder", "Ground Drill Bit", "Pump", "Tracktor" }));
        productname_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productname_tfActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(2.0F);
        jSeparator1.setAlignmentY(2.0F);
        jSeparator1.setOpaque(true);

        validate.setBackground(new java.awt.Color(255, 255, 255));
        validate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        validate.setOpaque(true);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel20Layout.createSequentialGroup()
                                    .addGap(226, 226, 226)
                                    .addComponent(model_t1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel20Layout.createSequentialGroup()
                                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(minrate_t2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(maxrate_t3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel20Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(yes_b)
                                    .addGap(35, 35, 35)
                                    .addComponent(no_b, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(img_text, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(validate, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66))))))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(model_t1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(productname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel20Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(209, 209, 209))
                                    .addGroup(jPanel20Layout.createSequentialGroup()
                                        .addComponent(img_text, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(validate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(177, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(minrate_t2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(maxrate_t3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yes_b)
                                    .addComponent(no_b, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150))))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("tab6", jPanel20);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setAlignmentX(0.1F);
        jScrollPane1.setAlignmentY(0.1F);
        jScrollPane1.setAutoscrolls(true);

        panelItem1.setBackground(new java.awt.Color(204, 255, 204));
        jScrollPane1.setViewportView(panelItem1);

        jTabbedPane1.addTab("tab6", jScrollPane1);

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout (1).png"))); // NOI18N
        jButton8.setText("Logout");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton8.setIconTextGap(23);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jTabbedPane1.addTab("tab5", jButton8);

        home_jPanel.add(jTabbedPane1);
        jTabbedPane1.setBounds(300, 30, 1070, 740);

        dashBoard_jPanel.setBackground(new java.awt.Color(28, 202, 139));

        home_jButton3.setBackground(new java.awt.Color(20, 22, 30));
        home_jButton3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        home_jButton3.setForeground(new java.awt.Color(255, 255, 255));
        home_jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home (5).png"))); // NOI18N
        home_jButton3.setText("Home");
        home_jButton3.setAlignmentY(0.0F);
        home_jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        home_jButton3.setFocusable(false);
        home_jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        home_jButton3.setIconTextGap(90);
        home_jButton3.setInheritsPopupMenu(true);
        home_jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        home_jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(20, 22, 30));
        jButton4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/product (1).png"))); // NOI18N
        jButton4.setText("add new");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton4.setIconTextGap(70);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(20, 22, 30));
        jButton5.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report.png"))); // NOI18N
        jButton5.setText("Report");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton5.setIconTextGap(85);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agricultural (1).png"))); // NOI18N
        jLabel3.setOpaque(true);

        jButton14.setBackground(new java.awt.Color(20, 22, 30));
        jButton14.setFont(new java.awt.Font("Microsoft JhengHei", 1, 20)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/password (1).png"))); // NOI18N
        jButton14.setText("Change Password");
        jButton14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton14.setIconTextGap(30);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashBoard_jPanelLayout = new javax.swing.GroupLayout(dashBoard_jPanel);
        dashBoard_jPanel.setLayout(dashBoard_jPanelLayout);
        dashBoard_jPanelLayout.setHorizontalGroup(
            dashBoard_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashBoard_jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(95, 95, 95))
            .addGroup(dashBoard_jPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(dashBoard_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dashBoard_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(home_jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        dashBoard_jPanelLayout.setVerticalGroup(
            dashBoard_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashBoard_jPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(home_jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        home_jPanel.add(dashBoard_jPanel);
        dashBoard_jPanel.setBounds(0, 60, 300, 710);

        getContentPane().add(home_jPanel);
        home_jPanel.setBounds(-10, 0, 1390, 770);

        setSize(new java.awt.Dimension(1396, 778));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_button3ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_button5ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_button2ActionPerformed

    private void home_jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_jButton3ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_home_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int productowned_count ;
        yes_b.setActionCommand("Yes");
        no_b.setActionCommand("No");
        String bool = buttonGroup1.getSelection().getActionCommand();
        String product;
            product = (String) productname_tf.getSelectedItem();
            if("mustfill".equals(product))
            {
               // JOptionPane.showMessageDialog(null, "Must select product Name");
                validate.setText("Must select product Nameol");
            }
            else
            {
          
                String sql = "";
                if("Drone".equals(product))
                {
                     sql = "insert into product(modelnumber,photo,minimumrate,maxrate,instructions,Descriptions,user_id,operator) values(?,?,?,?,?,?,?,?)";
                }
                else if("Brushcutter".equals(product))
                {
                    sql = "insert into product_2(modelnumber,photo,minimumrate,maxrate,instructions,Descriptions,user_id,operator) values(?,?,?,?,?,?,?,?)";

                }
                else if("Mini Power Weeder".equals(product))
                {
                    sql = "insert into product3(modelnumber,photo,minimumrate,maxrate,instructions,Descriptions,user_id,operator) values(?,?,?,?,?,?,?,?)";

                }
                else if("Ground Drill Bit".equals(product))
                {
                    sql = "insert into product_4(modelnumber,photo,minimumrate,maxrate,instructions,Descriptions,user_id,operator) values(?,?,?,?,?,?,?,?)";

                }
                else if("Pump".equals(product))
                {
                    sql = "insert into product_5(modelnumber,photo,minimumrate,maxrate,instructions,Descriptions,user_id,operator) values(?,?,?,?,?,?,?,?)";

                }
                else if("Tracktor".equals(product))
                {
                    sql = "insert into product_6(modelnumber,photo,minimumrate,maxrate,instructions,Descriptions,user_id,operator) values(?,?,?,?,?,?,?,?)";

                }
            

                try {
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/uzhavan","root","");
                    PreparedStatement ps = con.prepareStatement(sql);
                    InputStream is = new FileInputStream(new File(s));
                    int n =1;
                    while(n !=0)
                    {
                        if(model_t1.getText() != null && minrate_t2.getText() != null)
                        {
                            ps.setString(1,model_t1.getText());
                            ps.setBlob(2,is);
                            ps.setString(3, minrate_t2.getText());
                            ps.setString(4, maxrate_t3.getText());
                            ps.setString(5,instruction_t4.getText());
                            ps.setString(6,description_t5.getText());
                            ps.setInt(7, LoginForm.getUserId());
                            ps.setString(8, bool);
                            ps.executeUpdate();
                            n=0;
                            JOptionPane.showMessageDialog(null, "data inserted");
                            sql = "SELECT total_product_owned from user where user_id = '"+getUserId()+"'";
                            Statement stmt = con.createStatement();
                            ResultSet rs = stmt.executeQuery(sql);
                            if(rs.next())
                            {
                                productowned_count = rs.getInt(1);
                                productowned_count = productowned_count+1;
                                sql = "UPDATE user set total_product_owned = '" + productowned_count + "' WHERE user_id = '" + getUserId()+ "'";
                                stmt.executeUpdate(sql);
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "model number need");

                        }
                    }
                }catch(Exception ex)
                {
                    JFrame frame = new JFrame();
                    JOptionPane.showMessageDialog(frame,ex,"Error",JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();

                }
                   jTabbedPane1.setSelectedIndex(0);
                   //model_t1.setText("");
                   
                   
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void yes_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes_bActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_yes_bActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String fileName = f.getAbsolutePath();
        s = fileName;
        Image getAbsolutePath = null;
        img_text.setText(fileName);
        ImageIcon icon = new ImageIcon(fileName);
        Image image = icon.getImage();
        Image myImg = image.getScaledInstance(383,215, Image.SCALE_SMOOTH);
        ImageIcon newImage = new ImageIcon(myImg);
        img.setIcon(newImage);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String str = "SELECT product_no,product3.user_id,modelnumber,photo,minimumrate,maxrate,instructions,Descriptions,name FROM user INNER JOIN product3 on user.user_id = product3.user_id";
        PRODUCTNAME = "Mini Power Weeder";
        LoadProduct(str);
        jTabbedPane1.setSelectedIndex(3);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String str = "SELECT product_no,product_2.user_id,modelnumber,photo,minimumrate,maxrate,instructions,Descriptions,name FROM user INNER JOIN product_2 on user.user_id = product_2.user_id";
        PRODUCTNAME = "Brushcutter";
        LoadProduct(str);
        jTabbedPane1.setSelectedIndex(3);
        
       
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String str = "SELECT product_no,product_4.user_id,modelnumber,photo,minimumrate,maxrate,instructions,Descriptions,name FROM user INNER JOIN product_4 on user.user_id = product_4.user_id";
         PRODUCTNAME = "Ground Drill Bit";
         LoadProduct(str);
         jTabbedPane1.setSelectedIndex(3);
         
       
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
        String str = "SELECT product_no,product.user_id,modelnumber,photo,minimumrate,maxrate,instructions,Descriptions,name FROM user INNER JOIN product on user.user_id = product.user_id";
        PRODUCTNAME = "Drone";
        LoadProduct(str);
        jTabbedPane1.setSelectedIndex(3);
        
        
        
       
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String str = "SELECT product_no,product_5.user_id,modelnumber,photo,minimumrate,maxrate,instructions,Descriptions,name FROM user INNER JOIN product_5 on user.user_id = product_5.user_id";
          PRODUCTNAME = "Pump";
         LoadProduct(str);
         jTabbedPane1.setSelectedIndex(3);
         PRODUCTNAME = "Pump";
       

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        
        String str = "SELECT product_no,product_6.user_id,modelnumber,photo,minimumrate,maxrate,instructions,Descriptions,name FROM user INNER JOIN product_6 on user.user_id = product_6.user_id";
         PRODUCTNAME = "Tracktor";
         LoadProduct(str);
        jTabbedPane1.setSelectedIndex(3);
        PRODUCTNAME = "Tracktor";
    }//GEN-LAST:event_jButton13ActionPerformed

    private void model_t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_model_t1ActionPerformed

    private void model_t1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_model_t1FocusGained
        // TODO add your handling code here:
        if(model_t1.getText().equals("AB2022VL0967"))
        {
            model_t1.setText("");
            model_t1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_model_t1FocusGained

    private void model_t1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_model_t1FocusLost
        // TODO add your handling code here:
        validate.setText("");
        if(model_t1.getText().equals(""))
        {
            model_t1.setText("AB2022VL0967");
            model_t1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_model_t1FocusLost

    private void minrate_t2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_minrate_t2FocusGained
        // TODO add your handling code here:
        if(minrate_t2.getText().equals("Minium fixed rate"))
        {
            minrate_t2.setText("");
            minrate_t2.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_minrate_t2FocusGained

    private void minrate_t2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_minrate_t2FocusLost
        // TODO add your handling code here:
        if(minrate_t2.getText().equals(""))
        {
            minrate_t2.setText("Minium fixed rate");
            minrate_t2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_minrate_t2FocusLost
/**/
    private void maxrate_t3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_maxrate_t3FocusLost
        // TODO add your handling code here:
        if(maxrate_t3.getText().equals(""))
        {
            maxrate_t3.setText("Rate for 1-hour");
            maxrate_t3.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_maxrate_t3FocusLost

    private void maxrate_t3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_maxrate_t3FocusGained
        // TODO add your handling code here:
         validate.setText("");
         if(maxrate_t3.getText().equals("Rate for 1-hour"))
        {
            maxrate_t3.setText("");
            maxrate_t3.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_maxrate_t3FocusGained

    private void instruction_t4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_instruction_t4FocusGained
        // TODO add your handling code here:
        validate.setText("");
         if(instruction_t4.getText().equals(" Detailed instruction to handle the \n"+"product"))
        {
            instruction_t4.setText("");
            instruction_t4.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_instruction_t4FocusGained

    private void instruction_t4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_instruction_t4FocusLost
        // TODO add your handling code here:
         if(instruction_t4.getText().equals(""))
        {
            instruction_t4.setText(" Detailed instruction to handle the \n"+"product");
            instruction_t4.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_instruction_t4FocusLost

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        LoginForm lg = new LoginForm();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void reportUser_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reportUser_idFocusGained
        // TODO add your handling code here:
        if(reportUser_id.getText().equals("123"))
        {
           reportUser_id.setText("");
           reportUser_id.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_reportUser_idFocusGained

    private void reportUser_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reportUser_idFocusLost
        // TODO add your handling code here:
     if(instruction_t4.getText().equals(""))
        {
            reportUser_id.setText("123");
            reportUser_id.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_reportUser_idFocusLost

    private void reprtUser_NameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reprtUser_NameFocusGained
        // TODO add your handling code here:
        if(reprtUser_Name.getText().equals("Name"))
        {
           reprtUser_Name.setText("");
           reprtUser_Name.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_reprtUser_NameFocusGained

    private void reprtUser_NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reprtUser_NameFocusLost
        // TODO add your handling code here:
        if(reprtUser_Name.getText().equals(""))
        {
            reprtUser_Name.setText("Name");
            reprtUser_Name.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_reprtUser_NameFocusLost

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        int userId_to_report  = Integer.parseInt(reportUser_id.getText());
        String Name = reprtUser_Name.getText();
        int userID_By_report = getUserId();
        String reportStatement = report_tf.getText();
       String sql1 = "SELECT * from user where user_id='"+userId_to_report+"'";
       
        
        try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/uzhavan","root","");
                String sql = "insert into admin(user_id,reports,username,reported_by) values(?,?,?,?)";
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(sql1);
                if(rs.next())
                {


                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setInt(1,userId_to_report);
                    ps.setString(3, Name);
                    ps.setString(2, reportStatement);
                    ps.setInt(4, userID_By_report);
                    ps.executeUpdate();
                    sql = "SELECT negative_poll from user where user_id = "+userId_to_report;
                    rs = stmt.executeQuery(sql); 
                    if(rs.next())
                    {
                        int count = rs.getInt(1);
                        count = count+1;
                        sql = "UPDATE user set negative_poll = '" + count + "' WHERE user_id = '" + userId_to_report+ "'";
                        stmt.executeUpdate(sql);
                    }
                    result.setText("The user is reported Successfully");
                    result2.setText("Action will be taken soon");
                    reportUser_id.setText("");
                    reprtUser_Name.setText("");
                    report_tf.setText("");
                }
                else
                {
                    result.setText("the entered user is not available");
                    result2.setText("Please Enter the valid user  id");
                }
                
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
             result.setText("Please Enter the valid information");
        }
            
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void model_t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_model_t1KeyPressed
        // TODO add your handling code here:
        
        String min = model_t1.getText();
        int len = min.length();
        char c = evt.getKeyChar();
        if(Character.isLetterOrDigit(c)||Character.isISOControl(c))
        {
            if(len<15)
            {
                model_t1.setEditable(true);
                validate.setText("");
            }
            else{
                model_t1.setEditable(false);
                validate.setText("Maximum amount limit reached");
            }
        }
        else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode() == KeyEvent.VK_DELETE )
            {
                model_t1.setEditable(true);
                validate.setText("");
            }
            else{
                model_t1.setEditable(false);
                validate.setText("Please enter the Valid amount ");
            }
        }
    }//GEN-LAST:event_model_t1KeyPressed

    private void minrate_t2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minrate_t2KeyPressed
        // TODO add your handling code here:
        
        String min = minrate_t2.getText();
        int len = min.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar() <= '9')
        {
            if(len<4)
            {
                minrate_t2.setEditable(true);
                validate.setText("");
            }
            else{
                minrate_t2.setEditable(false);
                validate.setText("Maximum amount limit reached");
            }
        }
        else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode() == KeyEvent.VK_DELETE )
            {
                minrate_t2.setEditable(true);
                validate.setText("");
            }
            else{
                minrate_t2.setEditable(false);
                validate.setText("Please enter the Valid amount ");
            }
        }
    }//GEN-LAST:event_minrate_t2KeyPressed

    private void maxrate_t3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maxrate_t3KeyPressed
        // TODO add your handling code here:
        String max = maxrate_t3.getText();
        int len = max.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar() <= '9')
        {
            if(len<4)
            {
                maxrate_t3.setEditable(true);
                validate.setText("");
            }
            else{
                maxrate_t3.setEditable(false);
                validate.setText("Maximum amount limit reached");
            }
        }
        else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode() == KeyEvent.VK_DELETE )
            {
                maxrate_t3.setEditable(true);
                validate.setText("");
            }
            else{
                maxrate_t3.setEditable(false);
                validate.setText("Please enter the Valid amount ");
            }
        }
    }//GEN-LAST:event_maxrate_t3KeyPressed

    private void productname_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productname_tfActionPerformed
        // TODO add your handling code here:
        validate.setText("");
    }//GEN-LAST:event_productname_tfActionPerformed

    private void description_t5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_description_t5FocusGained
        // TODO add your handling code here:
               
        if( description_t5.getText().equals(" Detailed description about the \n"+"product "))
        {
            description_t5.setText("");
            description_t5.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_description_t5FocusGained

    private void description_t5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_description_t5FocusLost
        // TODO add your handling code here:\
        if(description_t5.getText().equals(""))
        {
            description_t5.setText(" Detailed description about the \n"+"product ");
            description_t5.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_description_t5FocusLost

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        ChangePassword ch = new ChangePassword();
        ch.setVisible(true);
        
    }//GEN-LAST:event_jButton14ActionPerformed

    private void user_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_nameMouseClicked
        // TODO add your handling code here:
        userdetails1 ud = new userdetails1();
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/uzhavan","root","");
            Statement stmt = con.createStatement();
            String sql = "SELECT * from user where user_id ="+getUserId();
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next())
            {
                String us = String.valueOf(rs.getInt(1));
                ud.user_id.setText(us);
                ud.name.setText((rs.getString(2)));
                ud.location.setText(rs.getString(3));
                ud.phonenmber.setText(rs.getString(4));
                ud.datepfbirth.setText(rs.getString(6));
                ud.city.setText(rs.getString(7));
                ud.stste.setText(rs.getString(8));
                ud.gender.setText(rs.getString(9));
                ud.emailid.setText(rs.getString(10));
                ud.aadharid.setText(rs.getString(11));
                ud.username.setText(rs.getString(13));
                us = String.valueOf(rs.getInt(14));
                ud.total_product_owned.setText(us);
                us = String.valueOf(rs.getInt(15));
                ud.total_product_rented.setText(us);
                us = String.valueOf(rs.getInt(16));
                ud.negative_poll.setText(us);
                
                }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
            
        ud.setVisible(true);
        
        
        
    }//GEN-LAST:event_user_nameMouseClicked

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
                LoginForm loginForm = new LoginForm();
                loginForm.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel dashBoard_jPanel;
    private javax.swing.JTextArea description_t5;
    private javax.swing.JButton home_jButton3;
    private javax.swing.JPanel home_jPanel;
    private javax.swing.JLabel img;
    private javax.swing.JTextField img_text;
    private javax.swing.JTextArea instruction_t4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    public static javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField maxrate_t3;
    private javax.swing.JTextField minrate_t2;
    private javax.swing.JTextField model_t1;
    private javax.swing.JRadioButton no_b;
    private Layout.PanelItem panelItem1;
    private javax.swing.JComboBox<String> productname_tf;
    private javax.swing.JTextField reportUser_id;
    private javax.swing.JTextArea report_tf;
    private javax.swing.JTextField reprtUser_Name;
    private javax.swing.JLabel result;
    private javax.swing.JLabel result2;
    private javax.swing.JPanel search_jPanel;
    public static javax.swing.JLabel user_id;
    public static javax.swing.JLabel user_name;
    private javax.swing.JLabel validate;
    private javax.swing.JRadioButton yes_b;
    // End of variables declaration//GEN-END:variables
}
