/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Conntentpanel;
import dashboard.MainMenu;
//import static java.awt.Image.SCALE_SMOOTH;
//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.Statement;
//import java.sql.*;
//import java.util.logging.Level;
//import java.util.logging.Logger;
/**
 *
 * @author Durai
 */
public class ItemDisplay extends javax.swing.JPanel {
    public static productPanel p1 = new productPanel();
    public String instruction,description,modelno,minrate,maxrate,Product_name;
    public  int USERIDPRODUCT;
    /**
     * Creates new form NewJPanel
     */
    public ItemDisplay() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photo = new javax.swing.JLabel();
        productname = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        action = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        product_number = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        photo.setForeground(new java.awt.Color(255, 255, 204));
        photo.setText("jLabel1");

        productname.setBackground(new java.awt.Color(255, 255, 255));
        productname.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        productname.setForeground(new java.awt.Color(181, 184, 190));
        productname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/items (1).png"))); // NOI18N
        productname.setText("    name");
        productname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 1, true));
        productname.setOpaque(true);

        rate.setBackground(new java.awt.Color(255, 255, 255));
        rate.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        rate.setForeground(new java.awt.Color(181, 184, 190));
        rate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ruppes.png"))); // NOI18N
        rate.setText(" description");
        rate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(199, 243, 226)));
        rate.setOpaque(true);

        action.setBackground(new java.awt.Color(51, 255, 204));
        action.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        action.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/details (1).png"))); // NOI18N
        action.setText("View more");
        action.setBorder(null);
        action.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        action.setIconTextGap(30);
        action.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionActionPerformed(evt);
            }
        });

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/owner.png"))); // NOI18N
        name.setText("Name");
        name.setIconTextGap(15);
        name.setOpaque(true);

        product_number.setBackground(new java.awt.Color(255, 255, 255));
        product_number.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        product_number.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productname, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(product_number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(action, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(product_number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(action, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public static productPanel panel()
    {
        return p1;
    }
    private void actionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionActionPerformed
        // TODO add your handling code here:
        //productPanel p1 = new productPanel();
       
                   
            p1.modelname_l.setText(this.productname.getText());
            p1.photo.setIcon(this.photo.getIcon());
            p1.description_l.setText(this.description);
            p1.instruction_l.setText(this.instruction);
            p1.minrate_l.setText(this.minrate);
            p1.maxrate.setText(this.rate.getText());
            productPanel.USERPRODUCTID = this.USERIDPRODUCT;
            p1.productNmae_l.setText(this.name.getText()); 
            
            
       
        MainMenu.jTabbedPane1.add(p1);
        MainMenu.jTabbedPane1.setSelectedComponent(p1);
       
        
    }//GEN-LAST:event_actionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton action;
    public javax.swing.JLabel name;
    public javax.swing.JLabel photo;
    public javax.swing.JLabel product_number;
    public javax.swing.JLabel productname;
    public javax.swing.JLabel rate;
    // End of variables declaration//GEN-END:variables
}
