/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Conntentpanel;

import ChartFram.BillForm;
import ChartFram.BillForm;
import dashboard.MainMenu;
import java.awt.Color;
//import Conntentpanel.ItemDisplay.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static loginpage.LoginForm.USERID;

//import dashboard.MainMenu.*;
/**
 *
 * @author Durai
 */
public class productPanel extends javax.swing.JPanel {
    
    BillForm ch = new BillForm();
    static int USERPRODUCTID;
    public static int getuserId()
    {
        return USERPRODUCTID;
    }
    private static int duration;
    public static int getDuration()
    {
        return duration;
    }
    public void currentDate()
    {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        ch.date.setText(dtf.format(now));
    }
    public productPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        modelname_l = new javax.swing.JLabel();
        productNmae_l = new javax.swing.JLabel();
        minrate_l = new javax.swing.JLabel();
        maxrate = new javax.swing.JLabel();
        instruction_l = new javax.swing.JLabel();
        description_l = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        placeOrder_b = new javax.swing.JButton();
        Back_l = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        days_tf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        hours_tf = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1080, 689));

        photo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jSeparator1.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator1.setOpaque(true);

        modelname_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        modelname_l.setText("        MODEL NO");
        modelname_l.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 2, true));
        modelname_l.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                modelname_lFocusGained(evt);
            }
        });

        productNmae_l.setBackground(new java.awt.Color(255, 255, 255));
        productNmae_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        productNmae_l.setForeground(new java.awt.Color(45, 5, 41));
        productNmae_l.setText("       PRODUCT NAME");
        productNmae_l.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 1, true));
        productNmae_l.setOpaque(true);

        minrate_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        minrate_l.setForeground(new java.awt.Color(51, 0, 51));
        minrate_l.setText("        MINIMUM RATE");
        minrate_l.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 2, true));

        maxrate.setBackground(new java.awt.Color(255, 255, 255));
        maxrate.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        maxrate.setForeground(new java.awt.Color(0, 0, 51));
        maxrate.setText("      MAX RATE");
        maxrate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 2, true));

        instruction_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        instruction_l.setForeground(new java.awt.Color(51, 0, 51));
        instruction_l.setText("     iNSRTUCTION");
        instruction_l.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 2, true));

        description_l.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        description_l.setForeground(new java.awt.Color(51, 0, 51));
        description_l.setText("        DESCRIPTION");
        description_l.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 243, 226), 1, true));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Duration :");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        placeOrder_b.setBackground(new java.awt.Color(20, 22, 30));
        placeOrder_b.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        placeOrder_b.setForeground(new java.awt.Color(204, 255, 255));
        placeOrder_b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/order (1).png"))); // NOI18N
        placeOrder_b.setText("place order");
        placeOrder_b.setBorder(null);
        placeOrder_b.setIconTextGap(25);
        placeOrder_b.setOpaque(true);
        placeOrder_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrder_bActionPerformed(evt);
            }
        });

        Back_l.setBackground(new java.awt.Color(20, 22, 30));
        Back_l.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Back_l.setForeground(new java.awt.Color(255, 255, 255));
        Back_l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back (1).png"))); // NOI18N
        Back_l.setText("Back");
        Back_l.setBorder(null);
        Back_l.setIconTextGap(55);
        Back_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_lActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel12.setText("No of Days :");

        days_tf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        days_tf.setText("0");
        days_tf.setBorder(null);
        days_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                days_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                days_tfFocusLost(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel13.setText("Hours         :");

        hours_tf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hours_tf.setText("0");
        hours_tf.setBorder(null);
        hours_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hours_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hours_tfFocusLost(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(modelname_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(productNmae_l, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                        .addComponent(minrate_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maxrate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(instruction_l, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(placeOrder_b, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                                .addComponent(Back_l, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(description_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(hours_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(days_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(modelname_l, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productNmae_l, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(minrate_l, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(maxrate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(description_l, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(instruction_l, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(days_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hours_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placeOrder_b, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back_l, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Back_lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_lActionPerformed
        // TODO add your handling code here:
        photo.setText("hello");
        
        MainMenu.jTabbedPane1.remove(ItemDisplay.panel());
      
    }//GEN-LAST:event_Back_lActionPerformed

    private void placeOrder_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrder_bActionPerformed
        // TODO add your handling code here:
        int bill_No =0;
        try
        {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/uzhavan","root","");
            Statement stmt = con.createStatement();
             String sql = "SELECT * FROM rented_products_details order by bill_number DESC";
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next())
            {
                bill_No = rs.getInt(6);
                break;
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, " Data not fetched");
            ex.printStackTrace();

        }
        
        int  cost;
        int day =0;
        day = Integer.parseInt(days_tf.getText());
        int hour =0;
        hour= Integer.parseInt(hours_tf.getText());
        int min = Integer.parseInt(minrate_l.getText());
        int max = Integer.parseInt(maxrate.getText());
        String id = String.valueOf(USERPRODUCTID);
        String costS;
        if(day > 0)
        {
            cost =(day*24+hour)*min;
        }
        else if(hour < 1)
        {
             cost =(day*24+hour)*max;
        }
        else
        {
            cost =(day*24+hour)*min;
        }
        bill_No = bill_No+1;
        duration = day*24+hour;
        costS = String.valueOf(cost);
        String duraiton = String.valueOf(day)+" day, "+String.valueOf(hour)+" hours";
        String bill = String.valueOf(bill_No);
        try
        {
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/uzhavan","root","");
            String sql = "SELECT name,phonenumber,emailid,location from user where  user.user_id = "+USERPRODUCTID;
            PreparedStatement stmt =con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            if(rs.next())
            {
                ch.S_location_l.setText(rs.getString(4));
                ch.S_name_l.setText((rs.getString(1)));
                ch.S_phoneNo_l.setText(rs.getString(2));
                ch.S_mailid.setText(rs.getString(3));
                ch.modelNo_l.setText(this.modelname_l.getText());
                ch.product_Name_l.setText(MainMenu.PRODUCTNAME);
                ch.rate_l.setText(this.maxrate.getText());
                ch.cost.setText(costS);
                ch.photo_l.setIcon(this.photo.getIcon());
                ch.duration_l.setText(duraiton);
                ch.bill_No.setText(bill);
                ch.owner_id.setText(id);
                sql = "SELECT name,phonenumber,emailid,location from user where  user.user_id = "+USERID;
                stmt =con.prepareStatement(sql);
                rs = stmt.executeQuery();
                id = String.valueOf(USERID);
                if(rs.next())
            {
                ch.buyer_location.setText(rs.getString(4));
                ch.buyer_name.setText((rs.getString(1)));
                ch.buyer_phonenumber.setText(rs.getString(2));
                ch.buyer_mailid.setText(rs.getString(3));
                ch.buyer_id1.setText(id);
                 rs = stmt.executeQuery();
            }
                
                currentDate();
                ch.setVisible(true);
                              // MainMenu.mainMenuform.setVisible(false);
            }
            else{
                System.out.println("not visited");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Data cannot display");
            ex.printStackTrace();
        }
        
        
    }//GEN-LAST:event_placeOrder_bActionPerformed

    private void modelname_lFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modelname_lFocusGained
        // TODO add your handling code here:
         
    }//GEN-LAST:event_modelname_lFocusGained

    private void days_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_days_tfFocusGained
        // TODO add your handling code here:
         if(days_tf.getText().equals("0"))
        {
            days_tf.setText("");
            days_tf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_days_tfFocusGained

    private void days_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_days_tfFocusLost
        // TODO add your handling code here:
        if(days_tf.getText().equals(""))
        {
            days_tf.setText("0");
            days_tf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_days_tfFocusLost

    private void hours_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hours_tfFocusGained
        // TODO add your handling code here:
        if(hours_tf.getText().equals("0"))
        {
            hours_tf.setText("");
            hours_tf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_hours_tfFocusGained

    private void hours_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hours_tfFocusLost
        // TODO add your handling code here:
         if(hours_tf.getText().equals(""))
        {
            hours_tf.setText("0");
            hours_tf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_hours_tfFocusLost
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_l;
    private javax.swing.JTextField days_tf;
    public javax.swing.JLabel description_l;
    private javax.swing.JTextField hours_tf;
    public javax.swing.JLabel instruction_l;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JLabel maxrate;
    public javax.swing.JLabel minrate_l;
    public javax.swing.JLabel modelname_l;
    public javax.swing.JLabel photo;
    private javax.swing.JButton placeOrder_b;
    public javax.swing.JLabel productNmae_l;
    // End of variables declaration//GEN-END:variables
}
