
package signuppage;

import databaseConnector.DatabaseConnection;
import java.awt.Color;
import static java.awt.Color.white;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import loginpage.LoginForm;


public class SignupForm1 extends javax.swing.JFrame {
    private String name;
    private String userName;
    private String mailId;
    private String phoneNumber;
    private String password;
    private String aadharNumber;
    private String date;
    private String location;
    private String city;
    private String address;
    private String gender;
    /**
     * Creates new form signupform
     */
    private int userId;
   
    
    public SignupForm1() {
        initComponents();
        
        //userId = 1;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        password_tf = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        Name_tf = new javax.swing.JTextField();
        userName_tf = new javax.swing.JTextField();
        mailId_tf = new javax.swing.JTextField();
        phoneNumber_tf = new javax.swing.JTextField();
        location_tf = new javax.swing.JTextField();
        city_tf = new javax.swing.JTextField();
        state_tf = new javax.swing.JTextField();
        aadhar_tf = new javax.swing.JTextField();
        male_b = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        PhoneNumber_valitate = new javax.swing.JLabel();
        Aadhar_valitate = new javax.swing.JLabel();
        name_valitate = new javax.swing.JLabel();
        userNmae_valitate = new javax.swing.JLabel();
        password_validate = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 70));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 200));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Signup");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 180, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login (2).png"))); // NOI18N
        jButton1.setText("LOGIN");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.setIconTextGap(20);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 800, 180, 50));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign-in (1).png"))); // NOI18N
        jButton2.setText("SIGNUP");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.setIconTextGap(25);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 800, 190, 50));

        jSeparator2.setBackground(new java.awt.Color(0, 11, 5));
        jSeparator2.setForeground(new java.awt.Color(11, 1, 1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 124, 446, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 11, 5));
        jSeparator3.setForeground(new java.awt.Color(11, 1, 1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 176, 446, 9));

        jSeparator4.setBackground(new java.awt.Color(0, 11, 5));
        jSeparator4.setForeground(new java.awt.Color(11, 1, 1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 232, 446, 7));

        jSeparator5.setBackground(new java.awt.Color(0, 11, 5));
        jSeparator5.setForeground(new java.awt.Color(11, 1, 1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 286, 446, -1));

        jSeparator1.setBackground(new java.awt.Color(68, 6, 6));
        jSeparator1.setForeground(new java.awt.Color(41, 6, 6));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 360, 446, 22));

        password_tf.setForeground(new java.awt.Color(153, 153, 153));
        password_tf.setText("Password");
        password_tf.setBorder(null);
        password_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                password_tfFocusLost(evt);
            }
        });
        password_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_tfKeyPressed(evt);
            }
        });
        jPanel1.add(password_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 250, 35));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel8.setText("Gender:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, 83, 27));

        jSeparator6.setBackground(new java.awt.Color(14, 13, 13));
        jSeparator6.setForeground(new java.awt.Color(18, 17, 17));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 441, 446, 11));

        jSeparator7.setBackground(new java.awt.Color(23, 20, 20));
        jSeparator7.setForeground(new java.awt.Color(24, 22, 22));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 506, 446, 10));

        jSeparator8.setBackground(new java.awt.Color(19, 16, 16));
        jSeparator8.setForeground(new java.awt.Color(24, 22, 22));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 572, 446, 10));

        jSeparator9.setBackground(new java.awt.Color(18, 15, 15));
        jSeparator9.setForeground(new java.awt.Color(5, 4, 4));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 641, 446, 10));

        jSeparator10.setBackground(new java.awt.Color(13, 12, 12));
        jSeparator10.setForeground(new java.awt.Color(10, 9, 9));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 695, 446, 10));

        Name_tf.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        Name_tf.setForeground(new java.awt.Color(153, 153, 153));
        Name_tf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Name_tf.setText("Name123");
        Name_tf.setBorder(null);
        Name_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Name_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Name_tfFocusLost(evt);
            }
        });
        Name_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Name_tfKeyPressed(evt);
            }
        });
        jPanel1.add(Name_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 35));

        userName_tf.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        userName_tf.setForeground(new java.awt.Color(153, 153, 153));
        userName_tf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userName_tf.setText("User Name@123");
        userName_tf.setBorder(null);
        userName_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userName_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userName_tfFocusLost(evt);
            }
        });
        userName_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userName_tfKeyPressed(evt);
            }
        });
        jPanel1.add(userName_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 210, 35));

        mailId_tf.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        mailId_tf.setForeground(new java.awt.Color(153, 153, 153));
        mailId_tf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mailId_tf.setText("example123@gmail.com");
        mailId_tf.setBorder(null);
        mailId_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailId_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailId_tfFocusLost(evt);
            }
        });
        jPanel1.add(mailId_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 430, 35));

        phoneNumber_tf.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        phoneNumber_tf.setForeground(new java.awt.Color(153, 153, 153));
        phoneNumber_tf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        phoneNumber_tf.setText("Phone Number");
        phoneNumber_tf.setBorder(null);
        phoneNumber_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneNumber_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneNumber_tfFocusLost(evt);
            }
        });
        phoneNumber_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneNumber_tfKeyPressed(evt);
            }
        });
        jPanel1.add(phoneNumber_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 260, 35));

        location_tf.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        location_tf.setForeground(new java.awt.Color(153, 153, 153));
        location_tf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        location_tf.setText("Location");
        location_tf.setBorder(null);
        location_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                location_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                location_tfFocusLost(evt);
            }
        });
        jPanel1.add(location_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 430, 35));

        city_tf.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        city_tf.setForeground(new java.awt.Color(153, 153, 153));
        city_tf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        city_tf.setText("City");
        city_tf.setBorder(null);
        city_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                city_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                city_tfFocusLost(evt);
            }
        });
        jPanel1.add(city_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 430, 35));

        state_tf.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        state_tf.setForeground(new java.awt.Color(153, 153, 153));
        state_tf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        state_tf.setText("State");
        state_tf.setBorder(null);
        state_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                state_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                state_tfFocusLost(evt);
            }
        });
        jPanel1.add(state_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 420, 35));

        aadhar_tf.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        aadhar_tf.setForeground(new java.awt.Color(153, 153, 153));
        aadhar_tf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        aadhar_tf.setText("Aadhar id");
        aadhar_tf.setBorder(null);
        aadhar_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aadhar_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                aadhar_tfFocusLost(evt);
            }
        });
        aadhar_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aadhar_tfKeyPressed(evt);
            }
        });
        jPanel1.add(aadhar_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 230, 35));

        buttonGroup1.add(male_b);
        male_b.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        male_b.setText("male");
        jPanel1.add(male_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 730, 120, 30));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButton2.setText("female");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 730, -1, 30));

        PhoneNumber_valitate.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jPanel1.add(PhoneNumber_valitate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 220, 40));
        jPanel1.add(Aadhar_valitate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 200, 40));

        name_valitate.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jPanel1.add(name_valitate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 250, 40));

        userNmae_valitate.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jPanel1.add(userNmae_valitate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 220, 40));
        jPanel1.add(password_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 190, 40));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 760, 450, 10));

        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jDateChooser1.setIcon(null);
        jDateChooser1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 360, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("D.O.B");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 90, 40));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(255, 255, 255,50));
        jLabel15.setFont(new java.awt.Font("Yu Gothic Medium", 0, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Sign In Form");
        jLabel15.setOpaque(true);
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, 330, 80));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255,50));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/durai.png"))); // NOI18N
        jLabel14.setOpaque(true);
        jLabel14.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 390, 230));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/12_13_2022 7_19_04 .png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 590, 310));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255,50));
        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel13.setText("Welcome to UZHAVAN -ERA");
        jLabel13.setOpaque(true);
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 590, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2022-12-13 at 07.26.22.jpg"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -14, 420, 260));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2022-12-13 at 07.26.22.jpg"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 0, 390, 240));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2022-12-13 at 07.26.22.jpg"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 120, 380));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2022-12-13 at 07.26.22.jpg"))); // NOI18N
        jLabel5.setOpaque(true);
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 242, 90, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2022-12-13 at 07.26.22.jpg"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 610, 210));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2022-12-13 at 07.26.22.jpg"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 548, 190, 210));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2022-12-13 at 07.26.22.jpg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2022-12-13 at 07.26.22.jpg"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WhatsApp Image 2022-12-13 at 07.26.22.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField8ActionPerformed

    private void jPasswordField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField7ActionPerformed

    private void jPasswordField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField6ActionPerformed

    private void jPasswordField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void aadhar_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aadhar_tfKeyPressed
        // TODO add your handling code here:
        aadharNumber = aadhar_tf.getText();
        int len = aadharNumber.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar() <= '9')
        {
            if(len<12)
            {
                aadhar_tf.setEditable(true);
                Aadhar_valitate.setText("");
            }
            else{
                aadhar_tf.setEditable(false);
                Aadhar_valitate.setText("Maximum Length reached");
            }
        }
        else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode() == KeyEvent.VK_DELETE )
            {
                aadhar_tf.setEditable(true);
                Aadhar_valitate.setText("");
            }
            else{
                aadhar_tf.setEditable(false);
                Aadhar_valitate.setText("Please enter the numbers only");
            }
        }
    }//GEN-LAST:event_aadhar_tfKeyPressed

    private void aadhar_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aadhar_tfFocusLost
        // TODO add your handling code here:
        if(aadhar_tf.getText().equals(""))
        {
            aadhar_tf.setText("Aadhar id");
            aadhar_tf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_aadhar_tfFocusLost

    private void aadhar_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aadhar_tfFocusGained
        // TODO add your handling code here:
        if(aadhar_tf.getText().equals("Aadhar id"))
        {
            aadhar_tf.setText("");
            aadhar_tf.setForeground(new Color(0,0,0));
        }

    }//GEN-LAST:event_aadhar_tfFocusGained

    private void state_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_state_tfFocusLost
        // TODO add your handling code here:
        if(state_tf.getText().equals(""))
        {
            state_tf.setText("State");
            state_tf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_state_tfFocusLost

    private void state_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_state_tfFocusGained
        // TODO add your handling code here:
        if(state_tf.getText().equals("State"))
        {
            state_tf.setText("");
            state_tf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_state_tfFocusGained

    private void city_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_city_tfFocusLost
        // TODO add your handling code here:
        if(city_tf.getText().equals(""))
        {
            city_tf.setText("City");
            city_tf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_city_tfFocusLost

    private void city_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_city_tfFocusGained
        // TODO add your handling code here:
        if(city_tf.getText().equals("City"))
        {
            city_tf.setText("");
            city_tf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_city_tfFocusGained

    private void location_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_location_tfFocusLost
        // TODO add your handling code here:
        if(location_tf.getText().equals(""))
        {
            location_tf.setText("Location");
            location_tf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_location_tfFocusLost

    private void location_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_location_tfFocusGained
        // TODO add your handling code here:
        if(location_tf.getText().equals("Location"))
        {
            location_tf.setText("");
            location_tf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_location_tfFocusGained

    private void phoneNumber_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumber_tfKeyPressed
        // TODO add your handling code here:
        phoneNumber = phoneNumber_tf.getText();
        int len = phoneNumber.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar() <= '9')
        {
            if(len<10)
            {
                phoneNumber_tf.setEditable(true);
                PhoneNumber_valitate.setText("");
            }
            else{
                phoneNumber_tf.setEditable(false);
                PhoneNumber_valitate.setText("Maximum Length reached");
            }
        }
        else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode() == KeyEvent.VK_DELETE )
            {
                phoneNumber_tf.setEditable(true);
                PhoneNumber_valitate.setText("");
            }
            else{
                phoneNumber_tf.setEditable(false);
                PhoneNumber_valitate.setText("Please enter the numbers only");
            }
        }
    }//GEN-LAST:event_phoneNumber_tfKeyPressed

    private void phoneNumber_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumber_tfFocusLost
        // TODO add your handling code here:
        if(phoneNumber_tf.getText().equals(""))
        {
            phoneNumber_tf.setText("Phone Number");
            phoneNumber_tf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_phoneNumber_tfFocusLost

    private void phoneNumber_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumber_tfFocusGained
        // TODO add your handling code here:
        if(phoneNumber_tf.getText().equals("Phone Number"))
        {
            phoneNumber_tf.setText("");
            phoneNumber_tf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_phoneNumber_tfFocusGained

    private void mailId_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailId_tfFocusLost
        // TODO add your handling code here:
        if(mailId_tf.getText().equals(""))
        {
            mailId_tf.setText("example123@gmail.com");
            mailId_tf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_mailId_tfFocusLost

    private void mailId_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailId_tfFocusGained
        // TODO add your handling code here:
        if(mailId_tf.getText().equals("example123@gmail.com"))
        {
            mailId_tf.setText("");
            mailId_tf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_mailId_tfFocusGained

    private void userName_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userName_tfKeyPressed
        // TODO add your handling code here:
        userName = userName_tf.getText();
        int len = userName.length();
        char c = evt.getKeyChar();
        if(Character.isLetterOrDigit(c)||Character.isISOControl(c))
        {
            if(len<20)
            {
                userName_tf.setEditable(true);
                userNmae_valitate.setText("");
            }
            else{
                userName_tf.setEditable(false);
                userNmae_valitate.setText("Maximum Length reached");
            }
        }
        else{

            userName_tf.setEditable(false);
            userNmae_valitate.setText("Please enter the Alphabets or numbers only");

        }
    }//GEN-LAST:event_userName_tfKeyPressed

    private void userName_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userName_tfFocusLost
        // TODO add your handling code here:
        if(userName_tf.getText().equals(""))
        {
            userName_tf.setText("User Name@123");
            userName_tf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_userName_tfFocusLost

    private void userName_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userName_tfFocusGained
        // TODO add your handling code here:
        if(userName_tf.getText().equals("User Name@123"))
        {
            userName_tf.setText("");
            userName_tf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_userName_tfFocusGained

    private void Name_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Name_tfKeyPressed
        // TODO add your handling code here:
        name = Name_tf.getText();
        int len = name.length();
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isISOControl(c))
        {
            if(len<20)
            {
                Name_tf.setEditable(true);
                name_valitate.setText("");
            }
            else{
                Name_tf.setEditable(false);
                name_valitate.setText("Maximum Length reached");
            }
        }
        else{
            Name_tf.setEditable(false);
            name_valitate.setText("Please enter the Alphabets only");
        }

    }//GEN-LAST:event_Name_tfKeyPressed

    private void Name_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Name_tfFocusLost
        // TODO add your handling code here:
        if(Name_tf.getText().equals(""))
        {
            Name_tf.setText("Name123");
            Name_tf.setForeground(new Color(153,153,153));
        }

    }//GEN-LAST:event_Name_tfFocusLost

    private void Name_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Name_tfFocusGained
        // TODO add your handling code here:

        if(Name_tf.getText().equals("Name123"))
        {
            Name_tf.setText("");
            Name_tf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_Name_tfFocusGained

    private void password_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_tfKeyPressed
        // TODO add your handling code here:
        password = password_tf.getText();
        int len = password.length();
        char c = evt.getKeyChar();
        if(Character.isLetterOrDigit(c)||Character.isDefined(c)||Character.isISOControl(c))
        {
            if(len<8)
            {
                password_tf.setEditable(true);
                password_validate.setText("Enter Atleast 8 CHARACTERS");
            }
            else
            {
                password_tf.setEditable(true);
                password_validate.setText("");

            }
        }
        else{

            password_tf.setEditable(false);
            password_validate.setText("Please enter the valid password only");

        }

    }//GEN-LAST:event_password_tfKeyPressed

    private void password_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_tfFocusLost
        // TODO add your handling code here:
        if(password_tf.getText().equals(""))
        {
            password_tf.setText("Password");
            password_tf.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_password_tfFocusLost

    private void password_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_password_tfFocusGained
        // TODO add your handling code here:
        if(password_tf.getText().equals("Password"))
        {
            password_tf.setText("");
            password_tf.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_password_tfFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        male_b.setActionCommand("Male");
        jRadioButton2.setActionCommand("Female");
        gender = buttonGroup1.getSelection().getActionCommand();
        
        name =  Name_tf.getText();
        Name_tf.setText("Name123");
        Name_tf.setForeground(new Color(153,153,153));
        
        userName =  userName_tf.getText();
        userName_tf.setText("User Name@123");
        userName_tf.setForeground(new Color(153,153,153));        

        mailId =  mailId_tf.getText();
        mailId_tf.setText("example123@gmail.com");
        mailId_tf.setForeground(new Color(153,153,153));
        
        phoneNumber =  phoneNumber_tf.getText();
        phoneNumber_tf.setText("Phone Number");
        phoneNumber_tf.setForeground(new Color(153,153,153));
        
        aadharNumber = aadhar_tf.getText();
        aadhar_tf.setText("Aadhar id");
        aadhar_tf.setForeground(new Color(153,153,153));
        
        password =  password_tf.getText();
        password_tf.setText("Password");
        password_tf.setForeground(new Color(153,153,153));
        
        address = location_tf.getText();
        location_tf.setText("Location");
        location_tf.setForeground(new Color(153,153,153));
        
        city = city_tf.getText();
        city_tf.setText("City");
        city_tf.setForeground(new Color(153,153,153));
        
        location = state_tf.getText();
        state_tf.setText("State");
        state_tf.setForeground(new Color(153,153,153));
        
       
        date = ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        jDateChooser1.setCalendar(null);
        if(name != "Name123" && !name.isEmpty() && userName != "User Name@123" && !userName.isEmpty() && mailId !="example123@gmail.com" && !mailId.isEmpty()
            && phoneNumber !="Phone Number" && !phoneNumber.isEmpty()
            && password !="Password" && !password.isEmpty()){
            try{
                
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/uzhavan","root","");
                String sqlQuery = "INSERT INTO `user`(name, location, phonenumber, dateofbirth, city, state, gender, emailid, aadharid, password, username) VALUES (?, ?, ?, ?, ?,?,?,?,?,?,?)";
                PreparedStatement preparedStatement = con.prepareStatement(sqlQuery);
                preparedStatement.setString(1, name);
                preparedStatement.setString(2, address);
                preparedStatement.setString(11, userName);
                preparedStatement.setString(4, date);
                preparedStatement.setString(3, phoneNumber);
                preparedStatement.setString(5, city);
                preparedStatement.setString(6, location);
                preparedStatement.setString(7, gender);
                preparedStatement.setString(8, mailId);
                preparedStatement.setString(9, aadharNumber);
                preparedStatement.setString(10, password);
                System.out.println("****************************");
                preparedStatement.execute();
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,"User is successfully created","Success",JOptionPane.INFORMATION_MESSAGE);
                LoginForm loginForm = new LoginForm();
                loginForm.setVisible(true);
        this.dispose();
            }
            catch(SQLIntegrityConstraintViolationException e)
            {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame,e,"Error",JOptionPane.ERROR_MESSAGE);

            }
            catch(Exception e){
                JFrame frame = new JFrame();
                 e.printStackTrace();
                JOptionPane.showMessageDialog(frame,e,"Error",JOptionPane.ERROR_MESSAGE);
            }

        }
        else{
            JFrame frame = new JFrame();
            
            JOptionPane.showMessageDialog(frame,"Please fill all fields!","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new signupform().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aadhar_valitate;
    private javax.swing.JTextField Name_tf;
    private javax.swing.JLabel PhoneNumber_valitate;
    private javax.swing.JTextField aadhar_tf;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField city_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField location_tf;
    private javax.swing.JTextField mailId_tf;
    private javax.swing.JRadioButton male_b;
    private javax.swing.JLabel name_valitate;
    private javax.swing.JPasswordField password_tf;
    private javax.swing.JLabel password_validate;
    private javax.swing.JTextField phoneNumber_tf;
    private javax.swing.JTextField state_tf;
    private javax.swing.JTextField userName_tf;
    private javax.swing.JLabel userNmae_valitate;
    // End of variables declaration//GEN-END:variables
}
