package Changepassword;


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static loginpage.LoginForm.getUserId;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Muthu Pandi
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form changepassword
     */
    public ChangePassword() {
        initComponents();
        updateCaptcha();
        //System.out.println(createCaptcha()+ "********");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void updateCaptcha(){
        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 0, 18));
        String captcha = createCaptcha();
        jLabel5.setText(captcha);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aadhar_tf = new javax.swing.JTextField();
        newppassword = new javax.swing.JPasswordField();
        newpassword2 = new javax.swing.JPasswordField();
        oldpassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        validate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel1.setText("Old password:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 156, 153, 32));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel2.setText("Aaadhar id:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 68, 153, 32));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel3.setText("New password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 235, 153, 32));

        aadhar_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadhar_tfActionPerformed(evt);
            }
        });
        aadhar_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aadhar_tfKeyPressed(evt);
            }
        });
        jPanel1.add(aadhar_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 70, 194, 32));

        newppassword.setText("jPasswordField1");
        newppassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newppasswordActionPerformed(evt);
            }
        });
        jPanel1.add(newppassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 234, 160, 39));

        newpassword2.setText("jPasswordField1");
        newpassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassword2ActionPerformed(evt);
            }
        });
        jPanel1.add(newpassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 322, 160, 32));

        oldpassword.setText("jPasswordField1");
        oldpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpasswordActionPerformed(evt);
            }
        });
        oldpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                oldpasswordKeyPressed(evt);
            }
        });
        jPanel1.add(oldpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 154, 160, 40));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel4.setText("Re-enter new password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 322, 264, 32));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 387, 121, 39));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 387, 158, 39));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/replace.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 387, 53, 39));

        jButton2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 543, 158, 45));

        jButton3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 543, 158, 45));
        jPanel1.add(validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 410, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(423, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 349, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newpassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassword2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpassword2ActionPerformed

    private void aadhar_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadhar_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadhar_tfActionPerformed

    private void oldpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpasswordActionPerformed

    private void newppasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newppasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newppasswordActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        updateCaptcha();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String password;
        String adhaarId = aadhar_tf.getText();
        aadhar_tf.setText("");
        String OldPassword =  oldpassword.getText();
        oldpassword.setText("");
        String Newpassword2 =  newpassword2.getText();
        newpassword2.setText("");
        String newpassword  = newppassword.getText();
        newppassword.setText("");
        String enteredCaptcha = jTextField2.getText();
        jTextField2.setText("");
        String captcha =  jLabel5.getText();
        if(captcha.equals(enteredCaptcha)  ){
           try {
               Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/uzhavan","root","");
               String sql = "SELECT password from user where user_id ="+getUserId();
               Statement stmt = con.createStatement();
               ResultSet rs = stmt.executeQuery(sql);
               if(rs.next())
               {
                   password = rs.getString(1);
                   if(password.equals(OldPassword))
                   {
                       if(newpassword.equals(Newpassword2))
                        {
                            try{
                               con = DriverManager.getConnection("jdbc:mysql://localhost:3306/uzhavan","root","");
                                sql = "UPDATE user set password = '" + Newpassword2 + "' WHERE user_id = '" + getUserId()+ "'";
                                stmt = con.createStatement();
                                stmt.executeUpdate(sql);
                               System.out.println(Newpassword2);
                                System.out.println(getUserId());
                            }
                             catch(Exception e){
                                e.printStackTrace();
                            }
                        }
                       else
                       {
                           validate.setText("new password and reEntered password doesnot match ");
                       }
                   }
                   else
                   {
                       validate.setText("Old Password doesnot match");
                   }
               }
           } 
           catch (SQLException ex) {
               ex.printStackTrace();
           }
        } 
        else{
            JFrame frame = new JFrame();
            updateCaptcha();
            JOptionPane.showMessageDialog(frame,"please enter the valid captcha!","Warning",JOptionPane.WARNING_MESSAGE);
        }         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void oldpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oldpasswordKeyPressed
      
    }//GEN-LAST:event_oldpasswordKeyPressed

    private void aadhar_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aadhar_tfKeyPressed
        // TODO add your handling code here:
        String aadharNumber;
        aadharNumber = aadhar_tf.getText();
        int len = aadharNumber.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0' && evt.getKeyChar() <= '9')
        {
            if(len<12)
            {
                aadhar_tf.setEditable(true);
                validate.setText("");
            }
            else{
                aadhar_tf.setEditable(false);
                validate.setText("Maximum Length reached");
            }
        }
        else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE ||evt.getExtendedKeyCode() == KeyEvent.VK_DELETE )
            {
                aadhar_tf.setEditable(true);
                validate.setText("");
            }
            else{
                aadhar_tf.setEditable(false);
                validate.setText("Please enter the numbers only");
            }
        }
    }//GEN-LAST:event_aadhar_tfKeyPressed

    public String createCaptcha(){
        Random rand = new Random();
        String captcha = "";
        for(int i = 0; i <= 50; i++){
            int randomChar = Math.abs(rand.nextInt()) % 62;
            if(randomChar < 26){
                int charCode = randomChar + 65; 
//                System.out.println("Cap"+String.valueOf(charCode));
                captcha = captcha + (char)charCode;
            } else if(randomChar < 52){
                int charCode = (randomChar - 26) + 97; 
//                System.out.println("Sma"+String.valueOf(charCode));
                captcha = captcha + (char)charCode;
            } else {
                int charCode = (randomChar - 52) + 48;
//                System.out.println("Num"+String.valueOf(charCode));
                captcha = captcha + (char)charCode;
            }
            
            if(captcha.length() == 5){
                break;
            }
        }
        
        return captcha;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadhar_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPasswordField newpassword2;
    private javax.swing.JPasswordField newppassword;
    private javax.swing.JPasswordField oldpassword;
    private javax.swing.JLabel validate;
    // End of variables declaration//GEN-END:variables
}
